# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fc5c346eb01454de8d1df986b53575ee"
name = "branded-upside-app"
handle = "branded-upside-app-11"
application_url = "https://turning-hull-addressing-recommended.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "buddy-box-dev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://turning-hull-addressing-recommended.trycloudflare.com/auth/callback",
  "https://turning-hull-addressing-recommended.trycloudflare.com/auth/shopify/callback",
  "https://turning-hull-addressing-recommended.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
